# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 162dabb5b2d8037656ffaf40cc522a560823a623218a711f885dd971fef69935f8449161e33e6d51e7b87111dd6bafc654ec847a67ddad92268c5fb4cdbb85c3

test:
  secret_key_base: e93b957d42cd1d493dc090850dc2072ac58953c86c247bdae1729c0c093c8e0084de33a9f8157da2061092c84e8b8a56edc554bd9b3554e60896182014b52c62

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
